export const FETCH_APP_DATA_START = "FETCH_APP_DATA_START";
export const FETCH_APP_DATA_SUCCESS = "FETCH_APP_DATA_SUCCESS";
export const FETCH_APP_DATA_FAIL = "FETCH_APP_DATA_FAIL";

export const SET_TEAMS_DATA = "SET_TEAMS_DATA ";
export const SET_SCHEDULE_DATA = "SET_SCHEDULE_DATA ";

export const SET_STANDINGS_DATA = "SET_STANDINGS_DATA";
export const SET_GAMES_DATA = "SET_GAMES_DATA";

export const CHANGE_TEAM_WINS = "CHANGE_TEAM_WINS";
export const SET_CURRENT_WINNER = "SET_CURRENT_WINNER";
export const MATCH_RESET = "MATCH_RESET";
export const APP_RESET = "APP_RESET";
export const DELETE_TEAM_WINS = "	DELETE_TEAM_WINS";

export const START_UPDATE_SCHEDULE = "START_UPDATE_SCHEDULE";
export const SUCCESS_UPDATE_STANDINGS = "SUCCESS_UPDATE_STANDINGS";
export const SHOW_STATS = "SHOW_STATS";
export const CHANGE_SAVE_STATUS = "CHANGE_SAVE_STATUS ";
export const SET_INFO_TEXT = "SET_INFO_TEXT";
export const FAIL_UPDATE_STATS = "FAIL_UPDATE_STATS";






